# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_cmaq_output import InlineResponse200CmaqOutput  # noqa: F401,E501
from swagger_server import util


class InlineResponse200Values(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, variable: str=None, latitude: str=None, longitude: str=None, cmaq_output: List[InlineResponse200CmaqOutput]=None):  # noqa: E501
        """InlineResponse200Values - a model defined in Swagger

        :param variable: The variable of this InlineResponse200Values.  # noqa: E501
        :type variable: str
        :param latitude: The latitude of this InlineResponse200Values.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this InlineResponse200Values.  # noqa: E501
        :type longitude: str
        :param cmaq_output: The cmaq_output of this InlineResponse200Values.  # noqa: E501
        :type cmaq_output: List[InlineResponse200CmaqOutput]
        """
        self.swagger_types = {
            'variable': str,
            'latitude': str,
            'longitude': str,
            'cmaq_output': List[InlineResponse200CmaqOutput]
        }

        self.attribute_map = {
            'variable': 'variable',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'cmaq_output': 'cmaq_output'
        }

        self._variable = variable
        self._latitude = latitude
        self._longitude = longitude
        self._cmaq_output = cmaq_output

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Values':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_values of this InlineResponse200Values.  # noqa: E501
        :rtype: InlineResponse200Values
        """
        return util.deserialize_model(dikt, cls)

    @property
    def variable(self) -> str:
        """Gets the variable of this InlineResponse200Values.


        :return: The variable of this InlineResponse200Values.
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable: str):
        """Sets the variable of this InlineResponse200Values.


        :param variable: The variable of this InlineResponse200Values.
        :type variable: str
        """

        self._variable = variable

    @property
    def latitude(self) -> str:
        """Gets the latitude of this InlineResponse200Values.


        :return: The latitude of this InlineResponse200Values.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: str):
        """Sets the latitude of this InlineResponse200Values.


        :param latitude: The latitude of this InlineResponse200Values.
        :type latitude: str
        """

        self._latitude = latitude

    @property
    def longitude(self) -> str:
        """Gets the longitude of this InlineResponse200Values.


        :return: The longitude of this InlineResponse200Values.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: str):
        """Sets the longitude of this InlineResponse200Values.


        :param longitude: The longitude of this InlineResponse200Values.
        :type longitude: str
        """

        self._longitude = longitude

    @property
    def cmaq_output(self) -> List[InlineResponse200CmaqOutput]:
        """Gets the cmaq_output of this InlineResponse200Values.


        :return: The cmaq_output of this InlineResponse200Values.
        :rtype: List[InlineResponse200CmaqOutput]
        """
        return self._cmaq_output

    @cmaq_output.setter
    def cmaq_output(self, cmaq_output: List[InlineResponse200CmaqOutput]):
        """Sets the cmaq_output of this InlineResponse200Values.


        :param cmaq_output: The cmaq_output of this InlineResponse200Values.
        :type cmaq_output: List[InlineResponse200CmaqOutput]
        """

        self._cmaq_output = cmaq_output
